Comment.create(:id => 1, :post_id => 13)
Comment.create(:id => 2, :post_id => 14)
Comment.create(:id => 3, :post_id => 12, :user_id => 1)
Comment.create(:id => 4, :post_id => 12, :user_id => 1)
Comment.create(:id => 5, :body => "asdgasdhahaf", :post_id => 12, :user_id => 1)
Comment.create(:id => 6, :body => "wenawena", :post_id => 18, :user_id => 2)
Comment.create(:id => 7, :body => "ahora siiiiii po cohpare!", :post_id => 18, :user_id => 1)
Comment.create(:id => 8, :body => "shkompare", :post_id => 18, :user_id => 2)
Comment.create(:id => 9, :body => "YEEES", :post_id => 23, :user_id => 1)
Comment.create(:id => 10, :body => "ojkdfgadsga", :post_id => 22, :user_id => 1)
