Post.create(:id => 1, :title => "elpost", :content => "wena!", :user_id => 2)
Post.create(:id => 2, :title => "wenawena", :content => "wenasa!", :user_id => 1)
Post.create(:id => 3, :title => "post2 adansio", :content => "jandsglja\r\nag\r\ndagf\r\ngad\r\nga\r\n", :user_id => 1)
Post.create(:id => 4, :title => "ppos3adansio", :content => "asdoian\r\nasdfsad\r\nsadf\r\nsa\r\nasdfsa", :user_id => 1)
Post.create(:id => 5, :title => "dhdsfhsd", :content => "fghsfgh3sf3h5s1fg", :user_id => 2)
Post.create(:id => 6, :title => "fghsfgh", :content => "fgewrweagdfjkjh", :user_id => 2)
Post.create(:id => 7, :title => "okamakak", :content => "aert43y5ethsf\r\n\r\n\r\n\r\nadsgadsga\r\n\r\n\r\n\r\nasdg\r\n\r\n", :user_id => 2)
Post.create(:id => 8, :title => "fgjgdnvbncvbvg", :content => "6841321cxcvbghs3f", :user_id => 2)
Post.create(:id => 9, :title => "23456yhj", :content => "wertyjukdfgbnm", :user_id => 2)
Post.create(:id => 10, :title => "dfgxfgfgzf", :content => "tyj57jtdnxf6", :user_id => 2)
Post.create(:id => 11, :title => "2345678jhgfds<", :content => "gdhfgzxcb", :user_id => 3)
Post.create(:id => 12, :title => "dsfgdsfg", :content => "rhrth s", :user_id => 3)
Post.create(:id => 15, :title => "cxz", :content => "cxz", :user_id => 1)
Post.create(:id => 16, :title => "okdmgoa", :content => "kdmfhadn\r\ndmpgamnd\r\n\r\noamdgpamng\r\n", :user_id => 1)
Post.create(:id => 17, :title => "post 6", :content => "post 6\r\npost 6\r\npost 6\r\npost 6\r\npost 6\r\n", :user_id => 1)
Post.create(:id => 18, :title => "7", :content => "7\r\n7\r\n7\r\n7\r\n", :user_id => 1)
Post.create(:id => 19, :title => "yhnujm", :content => "hdfhafdh\r\nsadgsadg", :user_id => 2)
Post.create(:id => 20, :title => "asghfsdgf", :content => "123456789iuytrewsdfgh\r\nsad\r\nfsad", :user_id => 2)
Post.create(:id => 21, :title => "asdfhg", :content => "sdb\r\nsdfb\r\ndsfbds\r\nfb\r\ndsfs", :user_id => 1)
Post.create(:id => 22, :title => "sshhhhhkcompare", :content => "shkohpare!", :user_id => 2)
Post.create(:id => 23, :title => "terrible postsss", :content => "sadfsadfsadf", :user_id => 2)
